import math

from .state_artifact import ACTIVE_STATE_ARTIFACT

# Tag legend:
#   [PWT10] Penn World Tables 10.01
#   [WDI23] World Bank WDI 2023
#   [WEO25] IMF World Economic Outlook 2025
#   [IPCC_AR6] IPCC AR6 WG1/WG2
#   [DICE16] Nordhaus DICE-2016R2, used only where structure matches
#   [SIPRI23] SIPRI military spending database 2023
#   [GCP2023] Global Carbon Project fossil CO2 history used for emissions-scale refresh
#   [BACKTEST] Bundled 2015-2023 historical backtest calibration
#   [XSECTION] Cross-sectional identification on the bundled 2015 country slice
#   [PRIOR] Expert prior pending empirical calibration
#   [ARTIFACT] Pipeline-bound compiled-state artifact; only change via state rebuild

SOURCE_TAG_NOTES = {
    "PWT10": "Penn World Tables 10.01 cross-country medians and accounting priors.",
    "WDI23": "World Bank WDI 2023 world-average macro and fiscal shares.",
    "WEO25": "IMF World Economic Outlook 2025 debt and borrowing priors.",
    "IPCC_AR6": "IPCC AR6 physical climate parameters and carbon-cycle references.",
    "DICE16": "DICE-2016R2 parameters only where the equation family is structurally aligned.",
    "SIPRI23": "SIPRI military burden averages.",
    "GCP2023": "Global Carbon Project fossil CO2 history used to derive emissions scaling during manifest refresh.",
    "BACKTEST": "Historical backtest calibration against the bundled 2015-2023 GDP/CO2/temperature fixture.",
    "XSECTION": "Cross-sectional identification against the bundled 2015 country slice.",
    "PRIOR": "Expert prior in the current model, not yet empirically calibrated.",
    "ARTIFACT": "Pipeline-bound compiled-state artifact that must only change with a state rebuild.",
}

# Production block.
ALPHA_CAPITAL = 0.30  # [PWT10]
BETA_LABOR = 0.60  # [PWT10]
GAMMA_ENERGY = 0.042  # [BACKTEST] Stage B/C robust rolling baseline (2015-2023).
SAVINGS_BASE = 0.24  # [WDI23]
CAPITAL_DEPRECIATION = 0.05  # [PWT10]
SAVINGS_BASELINE_OFFSET = 0.70  # [PRIOR]
SAVINGS_STABILITY_SENS = 0.60  # [PRIOR]
SAVINGS_TENSION_SENS = 0.40  # [PRIOR]
SAVINGS_MIN = 0.05
SAVINGS_MAX = 0.40
TECH_OUTPUT_SENS = 0.60  # [PRIOR]
GDP_ADJUST_SPEED_BASE = 0.30  # [PRIOR]
GDP_ADJUST_SPEED_GAP_SENS = 0.35  # [PRIOR]
OBS_MAX_NEIGHBORS = 8  # [PRIOR]
POLICY_LOG_DEPTH = 3  # [PRIOR] Visible action/outcome memory horizon for agent prompts.

# TFP block.
TFP_RD_SHARE_SENS = 0.30  # [BACKTEST] Stage B/C robust rolling baseline (2015-2023).
TFP_TRADE_SPILLOVER_SENS = 0.30  # [PRIOR]
TFP_DRIFT = 0.01  # [PRIOR]
TFP_DIFFUSION_SENS = 0.02  # [PRIOR]
TFP_GROWTH_MIN = -0.05
TFP_GROWTH_MAX = 0.05

# Fiscal and sovereign block.
BASE_INTEREST_RATE = 0.02  # [WEO25]
DEBT_SPREAD_THRESHOLD = 0.60  # [PRIOR]
DEBT_SPREAD_LINEAR = 0.03  # [PRIOR]
DEBT_SPREAD_QUADRATIC = 0.10  # [PRIOR]
DEBT_SPREAD_RISK_BASE = 0.50  # [PRIOR]
DEBT_SPREAD_RISK_SENS = 0.50  # [PRIOR]
DEBT_SPREAD_FRAGILITY_BASE = 0.70  # [PRIOR]
DEBT_SPREAD_FRAGILITY_SENS = 0.60  # [PRIOR]
RATE_SPREAD_CAP = 0.25
RATE_MAX = 0.35
CONTAGION_DEBT_THRESHOLD = 0.90  # [PRIOR]
CONTAGION_SPREAD_SENS = 0.02  # [PRIOR]
CONTAGION_SPREAD_CAP = 0.05
TAX_RATE_BASE = 0.22  # [WDI23]
SOCIAL_SPEND_BASE = 0.15  # [WDI23]
MILITARY_SPEND_BASE = 0.035  # [SIPRI23]
CLIMATE_ADAPT_BASE = 0.005  # [PRIOR]
CLIMATE_ADAPT_RISK_SENS = 0.015  # [PRIOR]
MAX_NEW_DEBT_GDP = 0.05  # [WEO25]
RD_SPENDING_DECAY = 0.85  # [PRIOR]

# Climate and carbon-cycle block.
CARBON_POOL_FRACTIONS = (0.2173, 0.2240, 0.2824, 0.2763)  # [IPCC_AR6]
CARBON_POOL_TIMESCALES = (math.inf, 394.4, 36.54, 4.304)  # [IPCC_AR6]
ECS_DEFAULT = 3.0  # [IPCC_AR6]
ECS_MIN = 1.5  # [IPCC_AR6]
ECS_MAX = 4.0  # [IPCC_AR6]
F_NONCO2_DEFAULT = 0.40  # [IPCC_AR6]
F_NONCO2_BASE_YEAR = 2015  # [IPCC_AR6]
F_NONCO2_TREND = 0.012  # [IPCC_AR6]
HEAT_CAP_SURFACE = 18.0  # [BACKTEST] Stage B/C robust rolling baseline (2015-2023).
HEAT_CAP_DEEP = 100.0  # [DICE16]
OCEAN_EXCHANGE = 0.7  # [DICE16]
TEMP_NATURAL_VARIABILITY_SIGMA = 0.08  # [BACKTEST]
TEMP_BACKTEST_ENSEMBLE_SIZE = 8  # [BACKTEST]
FORCING_LOG_COEFF = 5.35  # [IPCC_AR6]
EMISSIONS_SCALE = ACTIVE_STATE_ARTIFACT.emissions_scale  # [GCP2023] Derived during manifest refresh and bound to the active state manifest.
TECH_DECARB_K = 0.12  # [PRIOR]
DECARB_RATE_OBSERVED_REFERENCE = (
    ACTIVE_STATE_ARTIFACT.decarb_reference_rate or ACTIVE_STATE_ARTIFACT.decarb_rate
)  # [DATA] GCP fossil CO2 / World Bank PPP GDP fit over 2000-2023 excluding 2020-2021; see misc/calibration/decarb_rate_calibration.json.
DECARB_RATE_STRUCTURAL = ACTIVE_STATE_ARTIFACT.decarb_rate  # [ARTIFACT] Pipeline-bound residual structural energy-transition rate.
# NOTE: Empirical CO2/GDP intensity decline is 0.016 (see misc/calibration/decarb_rate_calibration.json).
# The gap between the active 0.052 artifact rate and the empirical fit implicitly absorbs
# energy-mix shift and efficiency gains encoded in the 2015 base state. Decompose this
# compound parameter when the model gets an explicit energy sector / fossil phase-out layer.
DECARB_RATE = DECARB_RATE_STRUCTURAL  # Backward-compatible alias pending a full rename across the legacy layer.
STRUCTURAL_TRANSITION_POLICY_SENS = 0.50  # [PRIOR]
STRUCTURAL_TRANSITION_TAX_SENS = 0.05  # [PRIOR]
STRUCTURAL_TRANSITION_MULT_MIN = 1.0
STRUCTURAL_TRANSITION_MULT_MAX = 1.15
CO2_INTENSITY_FLOOR = 0.02  # [PRIOR]
FUEL_TAX_EMISSIONS_SENS = 0.12  # [PRIOR]
FUEL_TAX_EFFECT_MIN = 0.60
FUEL_TAX_EFFECT_MAX = 1.40
POLICY_REDUCTION_MAX = 0.90

# Climate damage and resilience block.
DAMAGE_QUAD_COEFF = 0.006  # [PRIOR]
DAMAGE_BENEFIT_PEAK = 0.30  # [PRIOR]
DAMAGE_BENEFIT_MAX = 0.006  # [PRIOR]
DAMAGE_BENEFIT_STDDEV = 0.50  # [PRIOR]
DAMAGE_RISK_ADJ = 0.005  # [PRIOR]
RESILIENCE_STABILITY_W = 0.40  # [PRIOR]
RESILIENCE_TECH_W = 0.30  # [PRIOR]
RESILIENCE_TRUST_W = 0.15  # [PRIOR]
RESILIENCE_ADAPT_W = 0.15  # [PRIOR]
RESILIENCE_TECH_REF = 2.0  # [PRIOR]
RESILIENCE_ADAPT_REF = 0.03  # [PRIOR]
BIODIVERSITY_RISK_DAMP = 0.60  # [PRIOR]
BIODIVERSITY_TEMP_DAMAGE = 0.004  # [PRIOR]

# Climate risk block.
CRISK_RESPONSE_RATE = 0.06  # [PRIOR]
CRISK_TEMP_SENSITIVITY = 0.45  # [PRIOR]
CRISK_BASE_CONST = 0.30  # [PRIOR]
CRISK_WATER_WEIGHT = 0.45  # [PRIOR]
CRISK_GINI_WEIGHT = 0.15  # [PRIOR]

# Extreme events block.
EVENT_BASE_PROB = 0.012  # [PRIOR]
EVENT_MAX_EXTRA_PROB = 0.07  # [PRIOR]
EVENT_TEMP_WARMING_SENS = 0.15  # [PRIOR]
EVENT_RESILIENCE_DAMP = 0.40  # [PRIOR]
EVENT_PROB_MAX = 0.50
EVENT_SEVERITY_BASE = 0.03  # [PRIOR]
EVENT_SEVERITY_RISK_SENS = 0.15  # [PRIOR]
EVENT_SEVERITY_RESILIENCE_DAMP = 0.50  # [PRIOR]
EVENT_POP_LOSS_BASE = 0.004  # [PRIOR]
EVENT_POP_LOSS_RISK_SENS = 0.015  # [PRIOR]
EVENT_POP_RESILIENCE_DAMP = 0.35  # [PRIOR]
EVENT_SHOCK_PENALTY_CAP = 0.10
EVENT_SHOCK_PENALTY_SEVERITY_SENS = 0.50  # [PRIOR]
EVENT_SHOCK_YEARS = 2
EVENT_TENSION_JUMP_BASE = 0.03  # [PRIOR]
EVENT_TENSION_JUMP_RISK_SENS = 0.10  # [PRIOR]
EVENT_TRUST_STABILITY_THRESHOLD = 0.60  # [PRIOR]
EVENT_TRUST_REWARD_BASE = 0.02  # [PRIOR]
EVENT_TRUST_REWARD_RESILIENCE_SENS = 0.02  # [PRIOR]
EVENT_TRUST_PENALTY_BASE = 0.02  # [PRIOR]
EVENT_TRUST_PENALTY_RISK_SENS = 0.03  # [PRIOR]

# Social and demographic block.
FOOD_RESERVE_WEIGHT = 0.20  # [PRIOR]
FOOD_AVAILABILITY_MAX = 2.0  # [PRIOR]
PROSPERITY_LOGIT_SENS = 1.20  # [PRIOR]
BASE_BIRTH_RATE = 0.025  # [WDI23]
BIRTH_GDP_PC_DECAY = 0.000001  # [PRIOR]
BIRTH_PROSPERITY_DAMP = 0.50  # [PRIOR]
BIRTH_SCARCITY_DAMP = 0.60  # [PRIOR]
BIRTH_GINI_DAMP = 0.30  # [PRIOR]
BIRTH_RATE_MIN = 0.006
BIRTH_RATE_MAX = 0.040
BASE_DEATH_RATE = 0.012  # [WDI23]
DEATH_GDP_PC_DECAY = 0.0000005  # [PRIOR]
DEATH_SCARCITY_SENS = 1.0  # [PRIOR]
DEATH_GINI_SENS = 0.40  # [PRIOR]
DEATH_PROSPERITY_DAMP = 0.20  # [PRIOR]
DEATH_RATE_MIN = 0.004
DEATH_RATE_MAX = 0.030
MIGRATION_BASE_RATE = 0.001  # [PRIOR]
MIGRATION_MAX_SHARE = 0.003  # [PRIOR]
MIGRATION_INCOME_PUSH_W = 0.60  # [PRIOR]
MIGRATION_CONFLICT_PUSH_W = 0.40  # [PRIOR]
MIGRATION_DEST_CONFLICT_DAMP = 0.50  # [PRIOR]
TRUST_GDP_PC_SENS = 0.00005  # [PRIOR]
TRUST_GDP_PC_REF = 10000.0  # [PRIOR]
TRUST_UNEMPLOYMENT_SENS = -0.025  # [PRIOR]
TRUST_INFLATION_SENS = -0.025  # [PRIOR]
TRUST_GINI_SENS = -0.0004  # [PRIOR]
TRUST_TENSION_SENS = -0.08  # [PRIOR]
TRUST_TENSION_THRESHOLD = 0.30  # [PRIOR]
INEQUALITY_EFFECT_SENS = 0.0005  # [PRIOR]
SOCIAL_STRESS_UNEMPLOYMENT_SENS = 0.01  # [PRIOR]
SOCIAL_STRESS_INFLATION_SENS = 0.005  # [PRIOR]
SOCIAL_TRUST_ANCHOR_SENS = 0.06  # [PRIOR]
SOCIAL_TRUST_ANCHOR_REF = 0.50  # [PRIOR]
GINI_GROWTH_SENS = 6.0  # [PRIOR]
GINI_RECESSION_SENS = 4.0  # [PRIOR]
GINI_RECESSION_TENSION_OFFSET = 0.50  # [PRIOR]
GINI_FISCAL_SENS = -60.0  # [PRIOR]
GINI_TENSION_SENS = 1.2  # [PRIOR]
GINI_TENSION_REF = 0.40  # [PRIOR]
GINI_MIN = 20.0
GINI_MAX = 70.0
REGIME_COLLAPSE_TRUST_THRESHOLD = 0.20  # [PRIOR]
REGIME_COLLAPSE_TENSION_THRESHOLD = 0.80  # [PRIOR]
REGIME_COLLAPSE_CAPITAL_MULT = 0.70  # [PRIOR]
REGIME_COLLAPSE_GDP_MULT = 0.80  # [PRIOR]
REGIME_COLLAPSE_DEBT_MULT = 0.70  # [PRIOR]
REGIME_COLLAPSE_TRUST_FLOOR = 0.25  # [PRIOR]
REGIME_COLLAPSE_TENSION_CAP = 0.60  # [PRIOR]
REGIME_COLLAPSE_STABILITY_HIT = 0.20  # [PRIOR]
DEBT_CRISIS_DEBT_THRESHOLD = 1.20  # [PRIOR]
DEBT_CRISIS_RATE_THRESHOLD = 0.12  # [PRIOR]
DEBT_CRISIS_DEBT_MULT = 0.60  # [PRIOR]
DEBT_CRISIS_GDP_MULT = 0.93  # [PRIOR] softened onset haircut to avoid overshoot in Argentina-like stress paths
DEBT_CRISIS_UNEMPLOYMENT_MAX = 0.30  # [PRIOR]
DEBT_CRISIS_UNEMPLOYMENT_HIT = 0.05  # [PRIOR]
DEBT_CRISIS_TRUST_HIT = 0.15  # [PRIOR]
DEBT_CRISIS_TENSION_HIT = 0.15  # [PRIOR]
DEBT_CRISIS_STABILITY_HIT = 0.15  # [PRIOR]
FX_CRISIS_EXTERNAL_DEBT_THRESHOLD = 0.50  # [PRIOR]
FX_CRISIS_CURRENT_ACCOUNT_DEFICIT_THRESHOLD = -0.04  # [PRIOR]
FX_CRISIS_RESERVE_MONTHS_THRESHOLD = 3.0  # [PRIOR]
FX_CRISIS_RESERVE_OFFSET_WEIGHT = 1.0  # [PRIOR]
FX_CRISIS_IMPORT_LEAKAGE_WEIGHT = 0.15  # [PRIOR]
FX_CRISIS_DEBT_MULT = 1.10  # [PRIOR]
FX_CRISIS_GDP_MULT = 0.85  # [PRIOR]
FX_CRISIS_UNEMPLOYMENT_HIT = 0.06  # [PRIOR]
FX_CRISIS_TRUST_HIT = 0.12  # [PRIOR]
FX_CRISIS_TENSION_HIT = 0.14  # [PRIOR]
FX_CRISIS_STABILITY_HIT = 0.12  # [PRIOR]
FX_CRISIS_PERSIST_GDP_MULT = 0.98  # [PRIOR]
FX_CRISIS_PERSIST_TRUST_HIT = 0.02  # [PRIOR]
FX_CRISIS_PERSIST_TENSION_HIT = 0.015  # [PRIOR]
FX_CRISIS_RECOVERY_RESERVE_MONTHS = 3.0  # [PRIOR]
FX_CRISIS_MAX_YEARS = 4  # [PRIOR]
# Crisis persistence guardrail-safe plateau candidate selected from
# misc/calibration/crisis_persistence_calibration.json.
DEBT_CRISIS_PERSIST_GDP_MULT = 0.965  # [DATA plateau-guardrail]
DEBT_CRISIS_PERSIST_TRUST_HIT = 0.025  # [DATA plateau-guardrail]
DEBT_CRISIS_PERSIST_TENSION_HIT = 0.02  # [DATA plateau-guardrail]
DEBT_CRISIS_EXIT_THRESHOLD = 0.70  # [DATA plateau-guardrail]
DEBT_CRISIS_EXIT_RATE = 0.08  # [DATA plateau-guardrail]
DEBT_CRISIS_MAX_YEARS = 6  # [DATA plateau-guardrail]
REGIME_CRISIS_PERSIST_GDP_MULT = 0.96  # [DATA plateau-guardrail]
REGIME_CRISIS_PERSIST_CAPITAL_MULT = 0.975  # [DATA plateau-guardrail]
REGIME_CRISIS_MAX_YEARS = 5  # [DATA plateau-guardrail]

# Metric block.
DEBT_STRESS_THRESHOLD = 1.0  # [PRIOR]
DEBT_STRESS_CAP = 3.0  # [PRIOR]
PROTEST_RISK_TENSION_W = 0.60  # [PRIOR]
PROTEST_RISK_DISTRUST_W = 0.30  # [PRIOR]
PROTEST_RISK_GINI_W = 0.10  # [PRIOR]
PROTEST_RISK_FRAGILITY_BASE = 0.50  # [PRIOR]
PROTEST_RISK_FRAGILITY_SENS = 0.50  # [PRIOR]

# Credit rating block.
CR_RATING_PRIME_MAX = 3  # [PRIOR]
CR_RATING_INVESTMENT_MAX = 12  # [PRIOR]
CR_RATING_SUB_INVESTMENT_MAX = 18  # [PRIOR]
CR_RATING_DISTRESSED_MAX = 23  # [PRIOR]
CR_RATING_MIN = 1  # [PRIOR]
CR_RATING_MAX = 26  # [PRIOR]
CR_SANCTION_PRESSURE_STRONG_WEIGHT = 2.0  # [PRIOR]
CR_SANCTION_PRESSURE_DIVISOR = 8.0  # [PRIOR]
CR_WAR_HIGH_CONFLICT_THRESHOLD = 0.55  # [PRIOR]
CR_WAR_MIL_PRESSURE_SCALE = 1.5  # [PRIOR]
CR_WAR_LINK_CONFLICT_W = 0.55  # [PRIOR]
CR_WAR_LINK_TRUST_W = 0.25  # [PRIOR]
CR_WAR_LINK_MILITARY_W = 0.20  # [PRIOR]
CR_WAR_NEXT_WAR_W = 0.65  # [PRIOR]
CR_WAR_NEXT_CONFLICT_PRONE_W = 0.20  # [PRIOR]
CR_WAR_NEXT_HAWKISH_W = 0.15  # [PRIOR]
CR_SANCTION_HOSTILITY_CONFLICT_W = 0.55  # [PRIOR]
CR_SANCTION_HOSTILITY_TRUST_W = 0.45  # [PRIOR]
CR_SANCTION_NEXT_HOSTILITY_W = 0.60  # [PRIOR]
CR_SANCTION_NEXT_PROPENSITY_W = 0.40  # [PRIOR]
CR_SOCIAL_GINI_LO = 30.0  # [PRIOR]
CR_SOCIAL_GINI_HI = 65.0  # [PRIOR]
CR_SOCIAL_UNEMPLOYMENT_LO = 0.05  # [PRIOR]
CR_SOCIAL_UNEMPLOYMENT_HI = 0.25  # [PRIOR]
CR_SOCIAL_INFLATION_LO = 0.02  # [PRIOR]
CR_SOCIAL_INFLATION_HI = 0.15  # [PRIOR]
CR_SOCIAL_FOOD_YEARS_CAP = 2.0  # [PRIOR]
CR_SOCIAL_FOOD_STRESS_W = 0.15  # [PRIOR]
CR_SOCIAL_STRUCTURAL_GINI_W = 0.30  # [PRIOR]
CR_SOCIAL_STRUCTURAL_UNEMPLOYMENT_W = 0.20  # [PRIOR]
CR_SOCIAL_STRUCTURAL_INFLATION_W = 0.15  # [PRIOR]
CR_SOCIAL_STRUCTURAL_WATER_W = 0.20  # [PRIOR]
CR_SOCIAL_MANAGEMENT_TRUST_W = 0.35  # [PRIOR]
CR_SOCIAL_MANAGEMENT_POLICY_W = 0.25  # [PRIOR]
CR_SOCIAL_MANAGEMENT_STABILITY_W = 0.20  # [PRIOR]
CR_SOCIAL_MANAGEMENT_SPENDING_W = 0.20  # [PRIOR]
CR_SOCIAL_SPENDING_LO = 0.04  # [PRIOR]
CR_SOCIAL_SPENDING_HI = 0.20  # [PRIOR]
CR_FINANCIAL_DEBT_GDP_LO = 0.6  # [PRIOR]
CR_FINANCIAL_DEBT_GDP_HI = 1.8  # [PRIOR]
CR_FINANCIAL_RATE_LO = 0.04  # [PRIOR]
CR_FINANCIAL_RATE_HI = 0.20  # [PRIOR]
CR_FINANCIAL_NOW_DEBT_W = 0.35  # [PRIOR]
CR_FINANCIAL_NOW_RATE_W = 0.25  # [PRIOR]
CR_FINANCIAL_NOW_STRESS_W = 0.25  # [PRIOR]
CR_FINANCIAL_NOW_CRISIS_W = 0.15  # [PRIOR]
CR_FINANCIAL_NEXT_STRESS_W = 0.65  # [PRIOR]
CR_FINANCIAL_NEXT_GROWTH_W = 0.35  # [PRIOR]
CR_FINANCIAL_BLEND_NOW_W = 0.60  # [PRIOR]
CR_FINANCIAL_BLEND_NEXT_W = 0.40  # [PRIOR]
CR_GROWTH_DETERIORATION_LO = 0.01  # [PRIOR]
CR_GROWTH_DETERIORATION_HI = 0.20  # [PRIOR]
CR_WAR_BLEND_AT_WAR_W = 0.60  # [PRIOR]
CR_WAR_BLEND_NEXT_W = 0.40  # [PRIOR]
CR_REV_PROTEST_W = 0.30  # [PRIOR]
CR_REV_TENSION_W = 0.25  # [PRIOR]
CR_REV_TRUST_W = 0.20  # [PRIOR]
CR_REV_FRAGILITY_W = 0.15  # [PRIOR]
CR_REV_TREND_W = 0.10  # [PRIOR]
CR_REV_TREND_LO = 0.0  # [PRIOR]
CR_REV_TREND_HI = 0.20  # [PRIOR]
CR_SOCIAL_RISK_REV_W = 0.55  # [PRIOR]
CR_SOCIAL_RISK_STRUCT_W = 0.30  # [PRIOR]
CR_SOCIAL_RISK_COLLAPSE_W = 0.15  # [PRIOR]
CR_SOCIAL_RISK_MANAGEMENT_W = 0.20  # [PRIOR]
CR_SANCTIONS_BLEND_NOW_W = 0.55  # [PRIOR]
CR_SANCTIONS_BLEND_NEXT_W = 0.45  # [PRIOR]
CR_RESERVE_ENERGY_YEARS = 3.0  # [PRIOR]
CR_RESERVE_FOOD_YEARS = 2.0  # [PRIOR]
CR_RESERVE_METALS_YEARS = 3.0  # [PRIOR]
CR_RESERVE_RISK_ENERGY_W = 0.50  # [PRIOR]
CR_RESERVE_RISK_FOOD_W = 0.30  # [PRIOR]
CR_RESERVE_RISK_METALS_W = 0.20  # [PRIOR]
CR_MACRO_GROWTH_W = 0.35  # [PRIOR]
CR_MACRO_UNEMPLOYMENT_W = 0.20  # [PRIOR]
CR_MACRO_INFLATION_W = 0.15  # [PRIOR]
CR_MACRO_FX_BUFFER_W = 0.15  # [PRIOR]
CR_MACRO_RESERVE_W = 0.15  # [PRIOR]
CR_MACRO_UNEMPLOYMENT_LO = 0.05  # [PRIOR]
CR_MACRO_UNEMPLOYMENT_HI = 0.22  # [PRIOR]
CR_MACRO_INFLATION_LO = 0.02  # [PRIOR]
CR_MACRO_INFLATION_HI = 0.12  # [PRIOR]
CR_MACRO_FX_BUFFER_CAP = 0.20  # [PRIOR]
CR_TOTAL_FINANCIAL_W = 0.25  # [PRIOR]
CR_TOTAL_WAR_W = 0.20  # [PRIOR]
CR_TOTAL_SOCIAL_W = 0.22  # [PRIOR]
CR_TOTAL_SANCTIONS_W = 0.13  # [PRIOR]
CR_TOTAL_MACRO_W = 0.20  # [PRIOR]

CALIBRATION_STATUS = {
    "ALPHA_CAPITAL": "validated",
    "BETA_LABOR": "validated",
    "GAMMA_ENERGY": "backtest",
    "SAVINGS_BASE": "validated",
    "CAPITAL_DEPRECIATION": "validated",
    "TFP_RD_SHARE_SENS": "backtest",
    "TFP_TRADE_SPILLOVER_SENS": "prior",
    "OBS_MAX_NEIGHBORS": "prior",
    "POLICY_LOG_DEPTH": "prior",
    "TAX_RATE_BASE": "validated",
    "SOCIAL_SPEND_BASE": "validated",
    "MILITARY_SPEND_BASE": "validated",
    "CLIMATE_ADAPT_BASE": "prior",
    "CLIMATE_ADAPT_RISK_SENS": "prior",
    "MAX_NEW_DEBT_GDP": "validated",
    "CARBON_POOL_FRACTIONS": "validated",
    "CARBON_POOL_TIMESCALES": "validated",
    "ECS_DEFAULT": "validated",
    "F_NONCO2_DEFAULT": "validated",
    "HEAT_CAP_SURFACE": "backtest",
    "FORCING_LOG_COEFF": "validated",
    "EMISSIONS_SCALE": "validated",
    "TEMP_NATURAL_VARIABILITY_SIGMA": "backtest",
    "TEMP_BACKTEST_ENSEMBLE_SIZE": "backtest",
    "TECH_DECARB_K": "prior",
    "DECARB_RATE_OBSERVED_REFERENCE": "data",
    "DECARB_RATE_STRUCTURAL": "artifact",
    "DECARB_RATE": "artifact",
    "STRUCTURAL_TRANSITION_POLICY_SENS": "prior",
    "STRUCTURAL_TRANSITION_TAX_SENS": "prior",
    "DAMAGE_QUAD_COEFF": "prior",
    "DAMAGE_BENEFIT_PEAK": "questionable",
    "DAMAGE_BENEFIT_MAX": "questionable",
    "DAMAGE_RISK_ADJ": "questionable",
    "CRISK_RESPONSE_RATE": "prior",
    "CRISK_TEMP_SENSITIVITY": "prior",
    "CRISK_WATER_WEIGHT": "prior",
    "CRISK_GINI_WEIGHT": "questionable",
    "EVENT_BASE_PROB": "prior",
    "EVENT_MAX_EXTRA_PROB": "prior",
    "EVENT_RESILIENCE_DAMP": "prior",
    "BASE_BIRTH_RATE": "validated",
    "BASE_DEATH_RATE": "validated",
    "MIGRATION_BASE_RATE": "prior",
    "TRUST_GINI_SENS": "prior",
    "GINI_FISCAL_SENS": "prior",
    "REGIME_COLLAPSE_TRUST_THRESHOLD": "prior",
    "REGIME_CRISIS_PERSIST_GDP_MULT": "data",
    "REGIME_CRISIS_PERSIST_CAPITAL_MULT": "data",
    "REGIME_CRISIS_MAX_YEARS": "data",
    "DEBT_CRISIS_DEBT_THRESHOLD": "prior",
    "DEBT_CRISIS_PERSIST_GDP_MULT": "data",
    "DEBT_CRISIS_PERSIST_TRUST_HIT": "data",
    "DEBT_CRISIS_PERSIST_TENSION_HIT": "data",
    "DEBT_CRISIS_EXIT_THRESHOLD": "data",
    "DEBT_CRISIS_EXIT_RATE": "data",
    "DEBT_CRISIS_MAX_YEARS": "data",
    "FX_CRISIS_EXTERNAL_DEBT_THRESHOLD": "prior",
    "FX_CRISIS_CURRENT_ACCOUNT_DEFICIT_THRESHOLD": "prior",
    "FX_CRISIS_RESERVE_MONTHS_THRESHOLD": "prior",
    "FX_CRISIS_RESERVE_OFFSET_WEIGHT": "prior",
    "FX_CRISIS_IMPORT_LEAKAGE_WEIGHT": "prior",
    "FX_CRISIS_DEBT_MULT": "prior",
    "FX_CRISIS_GDP_MULT": "prior",
    "FX_CRISIS_UNEMPLOYMENT_HIT": "prior",
    "FX_CRISIS_TRUST_HIT": "prior",
    "FX_CRISIS_TENSION_HIT": "prior",
    "FX_CRISIS_STABILITY_HIT": "prior",
    "FX_CRISIS_PERSIST_GDP_MULT": "prior",
    "FX_CRISIS_PERSIST_TRUST_HIT": "prior",
    "FX_CRISIS_PERSIST_TENSION_HIT": "prior",
    "FX_CRISIS_RECOVERY_RESERVE_MONTHS": "prior",
    "FX_CRISIS_MAX_YEARS": "prior",
    "PROTEST_RISK_TENSION_W": "prior",
    "PROTEST_RISK_DISTRUST_W": "prior",
    "PROTEST_RISK_GINI_W": "prior",
}
