import math

from .state_artifact import ACTIVE_STATE_ARTIFACT

# Tag legend:
#   [PWT10] Penn World Tables 10.01
#   [WDI23] World Bank WDI 2023
#   [WEO25] IMF World Economic Outlook 2025
#   [IPCC_AR6] IPCC AR6 WG1/WG2
#   [DICE16] Nordhaus DICE-2016R2, used only where structure matches
#   [SIPRI23] SIPRI military spending database 2023
#   [GCP2023] Global Carbon Project fossil CO2 history used for emissions-scale refresh
#   [PRIOR] Expert prior pending empirical calibration
#   [ARTIFACT] Pipeline-bound compiled-state artifact; only change via state rebuild

SOURCE_TAG_NOTES = {
    "PWT10": "Penn World Tables 10.01 cross-country medians and accounting priors.",
    "WDI23": "World Bank WDI 2023 world-average macro and fiscal shares.",
    "WEO25": "IMF World Economic Outlook 2025 debt and borrowing priors.",
    "IPCC_AR6": "IPCC AR6 physical climate parameters and carbon-cycle references.",
    "DICE16": "DICE-2016R2 parameters only where the equation family is structurally aligned.",
    "SIPRI23": "SIPRI military burden averages.",
    "GCP2023": "Global Carbon Project fossil CO2 history used to derive emissions scaling during manifest refresh.",
    "PRIOR": "Expert prior in the current model, not yet empirically calibrated.",
    "ARTIFACT": "Pipeline-bound compiled-state artifact that must only change with a state rebuild.",
}

# Production block.
ALPHA_CAPITAL = 0.30  # [PWT10]
BETA_LABOR = 0.60  # [PWT10]
GAMMA_ENERGY = 0.10  # [PRIOR]
SAVINGS_BASE = 0.24  # [WDI23]
CAPITAL_DEPRECIATION = 0.05  # [PWT10]
SAVINGS_BASELINE_OFFSET = 0.70  # [PRIOR]
SAVINGS_STABILITY_SENS = 0.60  # [PRIOR]
SAVINGS_TENSION_SENS = 0.40  # [PRIOR]
SAVINGS_MIN = 0.05
SAVINGS_MAX = 0.40
TECH_OUTPUT_SENS = 0.60  # [PRIOR]
GDP_ADJUST_SPEED_BASE = 0.30  # [PRIOR]
GDP_ADJUST_SPEED_GAP_SENS = 0.35  # [PRIOR]

# TFP block.
TFP_RD_SHARE_SENS = 2.0  # [PRIOR]
TFP_TRADE_SPILLOVER_SENS = 0.30  # [PRIOR]
TFP_DRIFT = 0.01  # [PRIOR]
TFP_DIFFUSION_SENS = 0.02  # [PRIOR]
TFP_GROWTH_MIN = -0.05
TFP_GROWTH_MAX = 0.05

# Fiscal and sovereign block.
BASE_INTEREST_RATE = 0.02  # [WEO25]
DEBT_SPREAD_THRESHOLD = 0.60  # [PRIOR]
DEBT_SPREAD_LINEAR = 0.03  # [PRIOR]
DEBT_SPREAD_QUADRATIC = 0.10  # [PRIOR]
DEBT_SPREAD_RISK_BASE = 0.50  # [PRIOR]
DEBT_SPREAD_RISK_SENS = 0.50  # [PRIOR]
DEBT_SPREAD_FRAGILITY_BASE = 0.70  # [PRIOR]
DEBT_SPREAD_FRAGILITY_SENS = 0.60  # [PRIOR]
RATE_SPREAD_CAP = 0.25
RATE_MAX = 0.35
CONTAGION_DEBT_THRESHOLD = 0.90  # [PRIOR]
CONTAGION_SPREAD_SENS = 0.02  # [PRIOR]
CONTAGION_SPREAD_CAP = 0.05
TAX_RATE_BASE = 0.22  # [WDI23]
SOCIAL_SPEND_BASE = 0.15  # [WDI23]
MILITARY_SPEND_BASE = 0.035  # [SIPRI23]
CLIMATE_ADAPT_BASE = 0.005  # [PRIOR]
CLIMATE_ADAPT_RISK_SENS = 0.015  # [PRIOR]
MAX_NEW_DEBT_GDP = 0.05  # [WEO25]
RD_SPENDING_DECAY = 0.85  # [PRIOR]

# Climate and carbon-cycle block.
CARBON_POOL_FRACTIONS = (0.2173, 0.2240, 0.2824, 0.2763)  # [IPCC_AR6]
CARBON_POOL_TIMESCALES = (math.inf, 394.4, 36.54, 4.304)  # [IPCC_AR6]
ECS_DEFAULT = 3.0  # [IPCC_AR6]
ECS_MIN = 1.5  # [IPCC_AR6]
ECS_MAX = 4.0  # [IPCC_AR6]
F_NONCO2_DEFAULT = 0.40  # [IPCC_AR6]
F_NONCO2_BASE_YEAR = 2015  # [IPCC_AR6]
F_NONCO2_TREND = 0.012  # [IPCC_AR6]
HEAT_CAP_SURFACE = 20.0  # [DICE16]
HEAT_CAP_DEEP = 100.0  # [DICE16]
OCEAN_EXCHANGE = 0.7  # [DICE16]
FORCING_LOG_COEFF = 5.35  # [IPCC_AR6]
EMISSIONS_SCALE = ACTIVE_STATE_ARTIFACT.emissions_scale  # [GCP2023] Derived during manifest refresh and bound to the active state manifest.
TECH_DECARB_K = 0.12  # [PRIOR]
DECARB_RATE = ACTIVE_STATE_ARTIFACT.decarb_rate  # [ARTIFACT] Bound to active state manifest.
CO2_INTENSITY_FLOOR = 0.02  # [PRIOR]
FUEL_TAX_EMISSIONS_SENS = 0.12  # [PRIOR]
FUEL_TAX_EFFECT_MIN = 0.60
FUEL_TAX_EFFECT_MAX = 1.40
POLICY_REDUCTION_MAX = 0.90

# Climate damage and resilience block.
DAMAGE_QUAD_COEFF = 0.006  # [PRIOR]
DAMAGE_BENEFIT_PEAK = 0.30  # [PRIOR]
DAMAGE_BENEFIT_MAX = 0.006  # [PRIOR]
DAMAGE_BENEFIT_STDDEV = 0.50  # [PRIOR]
DAMAGE_RISK_ADJ = 0.005  # [PRIOR]
RESILIENCE_STABILITY_W = 0.40  # [PRIOR]
RESILIENCE_TECH_W = 0.30  # [PRIOR]
RESILIENCE_TRUST_W = 0.15  # [PRIOR]
RESILIENCE_ADAPT_W = 0.15  # [PRIOR]
RESILIENCE_TECH_REF = 2.0  # [PRIOR]
RESILIENCE_ADAPT_REF = 0.03  # [PRIOR]
BIODIVERSITY_RISK_DAMP = 0.60  # [PRIOR]
BIODIVERSITY_TEMP_DAMAGE = 0.004  # [PRIOR]

# Climate risk block.
CRISK_RESPONSE_RATE = 0.06  # [PRIOR]
CRISK_TEMP_SENSITIVITY = 0.45  # [PRIOR]
CRISK_BASE_CONST = 0.30  # [PRIOR]
CRISK_WATER_WEIGHT = 0.45  # [PRIOR]
CRISK_GINI_WEIGHT = 0.15  # [PRIOR]

# Extreme events block.
EVENT_BASE_PROB = 0.012  # [PRIOR]
EVENT_MAX_EXTRA_PROB = 0.07  # [PRIOR]
EVENT_TEMP_WARMING_SENS = 0.15  # [PRIOR]
EVENT_RESILIENCE_DAMP = 0.40  # [PRIOR]
EVENT_PROB_MAX = 0.50
EVENT_SEVERITY_BASE = 0.03  # [PRIOR]
EVENT_SEVERITY_RISK_SENS = 0.15  # [PRIOR]
EVENT_SEVERITY_RESILIENCE_DAMP = 0.50  # [PRIOR]
EVENT_POP_LOSS_BASE = 0.004  # [PRIOR]
EVENT_POP_LOSS_RISK_SENS = 0.015  # [PRIOR]
EVENT_POP_RESILIENCE_DAMP = 0.35  # [PRIOR]
EVENT_SHOCK_PENALTY_CAP = 0.10
EVENT_SHOCK_PENALTY_SEVERITY_SENS = 0.50  # [PRIOR]
EVENT_SHOCK_YEARS = 2
EVENT_TENSION_JUMP_BASE = 0.03  # [PRIOR]
EVENT_TENSION_JUMP_RISK_SENS = 0.10  # [PRIOR]
EVENT_TRUST_STABILITY_THRESHOLD = 0.60  # [PRIOR]
EVENT_TRUST_REWARD_BASE = 0.02  # [PRIOR]
EVENT_TRUST_REWARD_RESILIENCE_SENS = 0.02  # [PRIOR]
EVENT_TRUST_PENALTY_BASE = 0.02  # [PRIOR]
EVENT_TRUST_PENALTY_RISK_SENS = 0.03  # [PRIOR]

# Social and demographic block.
FOOD_RESERVE_WEIGHT = 0.20  # [PRIOR]
FOOD_AVAILABILITY_MAX = 2.0  # [PRIOR]
PROSPERITY_LOGIT_SENS = 1.20  # [PRIOR]
BASE_BIRTH_RATE = 0.025  # [WDI23]
BIRTH_GDP_PC_DECAY = 0.000001  # [PRIOR]
BIRTH_PROSPERITY_DAMP = 0.50  # [PRIOR]
BIRTH_SCARCITY_DAMP = 0.60  # [PRIOR]
BIRTH_GINI_DAMP = 0.30  # [PRIOR]
BIRTH_RATE_MIN = 0.006
BIRTH_RATE_MAX = 0.040
BASE_DEATH_RATE = 0.012  # [WDI23]
DEATH_GDP_PC_DECAY = 0.0000005  # [PRIOR]
DEATH_SCARCITY_SENS = 1.0  # [PRIOR]
DEATH_GINI_SENS = 0.40  # [PRIOR]
DEATH_PROSPERITY_DAMP = 0.20  # [PRIOR]
DEATH_RATE_MIN = 0.004
DEATH_RATE_MAX = 0.030
MIGRATION_BASE_RATE = 0.001  # [PRIOR]
MIGRATION_MAX_SHARE = 0.003  # [PRIOR]
MIGRATION_INCOME_PUSH_W = 0.60  # [PRIOR]
MIGRATION_CONFLICT_PUSH_W = 0.40  # [PRIOR]
MIGRATION_DEST_CONFLICT_DAMP = 0.50  # [PRIOR]
TRUST_GDP_PC_SENS = 0.00005  # [PRIOR]
TRUST_GDP_PC_REF = 10000.0  # [PRIOR]
TRUST_UNEMPLOYMENT_SENS = -0.025  # [PRIOR]
TRUST_INFLATION_SENS = -0.025  # [PRIOR]
TRUST_GINI_SENS = -0.0004  # [PRIOR]
TRUST_TENSION_SENS = -0.08  # [PRIOR]
TRUST_TENSION_THRESHOLD = 0.30  # [PRIOR]
INEQUALITY_EFFECT_SENS = 0.0005  # [PRIOR]
SOCIAL_STRESS_UNEMPLOYMENT_SENS = 0.01  # [PRIOR]
SOCIAL_STRESS_INFLATION_SENS = 0.005  # [PRIOR]
SOCIAL_TRUST_ANCHOR_SENS = 0.06  # [PRIOR]
SOCIAL_TRUST_ANCHOR_REF = 0.50  # [PRIOR]
GINI_GROWTH_SENS = 6.0  # [PRIOR]
GINI_RECESSION_SENS = 4.0  # [PRIOR]
GINI_RECESSION_TENSION_OFFSET = 0.50  # [PRIOR]
GINI_FISCAL_SENS = -60.0  # [PRIOR]
GINI_TENSION_SENS = 1.2  # [PRIOR]
GINI_TENSION_REF = 0.40  # [PRIOR]
GINI_MIN = 20.0
GINI_MAX = 70.0
REGIME_COLLAPSE_TRUST_THRESHOLD = 0.20  # [PRIOR]
REGIME_COLLAPSE_TENSION_THRESHOLD = 0.80  # [PRIOR]
REGIME_COLLAPSE_CAPITAL_MULT = 0.70  # [PRIOR]
REGIME_COLLAPSE_GDP_MULT = 0.80  # [PRIOR]
REGIME_COLLAPSE_DEBT_MULT = 0.70  # [PRIOR]
REGIME_COLLAPSE_TRUST_FLOOR = 0.25  # [PRIOR]
REGIME_COLLAPSE_TENSION_CAP = 0.60  # [PRIOR]
REGIME_COLLAPSE_STABILITY_HIT = 0.20  # [PRIOR]
DEBT_CRISIS_DEBT_THRESHOLD = 1.20  # [PRIOR]
DEBT_CRISIS_RATE_THRESHOLD = 0.12  # [PRIOR]
DEBT_CRISIS_DEBT_MULT = 0.60  # [PRIOR]
DEBT_CRISIS_GDP_MULT = 0.90  # [PRIOR]
DEBT_CRISIS_UNEMPLOYMENT_MAX = 0.30  # [PRIOR]
DEBT_CRISIS_UNEMPLOYMENT_HIT = 0.05  # [PRIOR]
DEBT_CRISIS_TRUST_HIT = 0.15  # [PRIOR]
DEBT_CRISIS_TENSION_HIT = 0.15  # [PRIOR]
DEBT_CRISIS_STABILITY_HIT = 0.15  # [PRIOR]

# Metric block.
DEBT_STRESS_THRESHOLD = 1.0  # [PRIOR]
DEBT_STRESS_CAP = 3.0  # [PRIOR]
PROTEST_RISK_TENSION_W = 0.60  # [PRIOR]
PROTEST_RISK_DISTRUST_W = 0.30  # [PRIOR]
PROTEST_RISK_GINI_W = 0.10  # [PRIOR]
PROTEST_RISK_FRAGILITY_BASE = 0.50  # [PRIOR]
PROTEST_RISK_FRAGILITY_SENS = 0.50  # [PRIOR]

CALIBRATION_STATUS = {
    "ALPHA_CAPITAL": "validated",
    "BETA_LABOR": "validated",
    "GAMMA_ENERGY": "prior",
    "SAVINGS_BASE": "validated",
    "CAPITAL_DEPRECIATION": "validated",
    "TFP_RD_SHARE_SENS": "prior",
    "TFP_TRADE_SPILLOVER_SENS": "prior",
    "TAX_RATE_BASE": "validated",
    "SOCIAL_SPEND_BASE": "validated",
    "MILITARY_SPEND_BASE": "validated",
    "CLIMATE_ADAPT_BASE": "prior",
    "CLIMATE_ADAPT_RISK_SENS": "prior",
    "MAX_NEW_DEBT_GDP": "validated",
    "CARBON_POOL_FRACTIONS": "validated",
    "CARBON_POOL_TIMESCALES": "validated",
    "ECS_DEFAULT": "validated",
    "F_NONCO2_DEFAULT": "validated",
    "FORCING_LOG_COEFF": "validated",
    "EMISSIONS_SCALE": "validated",
    "TECH_DECARB_K": "prior",
    "DECARB_RATE": "artifact",
    "DAMAGE_QUAD_COEFF": "prior",
    "DAMAGE_BENEFIT_PEAK": "questionable",
    "DAMAGE_BENEFIT_MAX": "questionable",
    "DAMAGE_RISK_ADJ": "questionable",
    "CRISK_RESPONSE_RATE": "prior",
    "CRISK_TEMP_SENSITIVITY": "prior",
    "CRISK_WATER_WEIGHT": "prior",
    "CRISK_GINI_WEIGHT": "questionable",
    "EVENT_BASE_PROB": "prior",
    "EVENT_MAX_EXTRA_PROB": "prior",
    "EVENT_RESILIENCE_DAMP": "prior",
    "BASE_BIRTH_RATE": "validated",
    "BASE_DEATH_RATE": "validated",
    "MIGRATION_BASE_RATE": "prior",
    "TRUST_GINI_SENS": "prior",
    "GINI_FISCAL_SENS": "prior",
    "REGIME_COLLAPSE_TRUST_THRESHOLD": "prior",
    "DEBT_CRISIS_DEBT_THRESHOLD": "prior",
    "PROTEST_RISK_TENSION_W": "prior",
    "PROTEST_RISK_DISTRUST_W": "prior",
    "PROTEST_RISK_GINI_W": "prior",
}
